[package]
name = "client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rpg-client"
path = "src/main.rs"

[dependencies]
chrono = "*"
piston = "*"
piston2d-graphics = "*"
piston_window = "*"
tokio = { version = "1.40.0", features = ["full"] }
tonic = "*"
prost = "*"
find_folder = "*"

serde_json = "*"
serde = {  version = "*", features = [ "derive" ] }
rand = "0.9.0"
tokio-stream = "0.1.17"

common = { path = "../common" }