[package]
name = "client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rpg-client"
path = "src/main.rs"

[dependencies]
chrono = "*"
piston = "0.53.0"
piston2d-graphics = "0.40.0"
piston_window = "0.119.0"
winit = "0.24"
image = "0.23"

tokio = { version = "1.40.0", features = ["full"] }
tonic = "*"
prost = "*"
find_folder = "*"

serde_json = "*"
serde = {  version = "*", features = [ "derive" ] }
rand = "0.9.0"
tokio-stream = "0.1.17"

common = { path = "../common" }