// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table accounts {
  id uuid [not null, primary key]
  login varchar(12) [not null, unique]
  password varchar(255) [not null]
  session_token varchar(255)
}

Table accounts_characters {
  account_id uuid [not null]
  character_id integer [not null] // TODO make this pair unique
}

Enum CLASS {
  Warrior
  Witcher
}

Table characters {
  id integer [not null, primary key]
  class CLASS [not null]
}

Table characters_entities {
  characters_id uuid [not null]
  entity_id integer [not null] // TODO make this pair unique
}

Table locations {
  entity_id varchar(12) [not null, unique]
  world point [not null]
  map point [not null]
}

Table entities {
  id integer [primary key]
  name varchar(12) [not null]
  level integer // Create TYPE where 10 <= level >= 1
  health_point integer 
}

Enum MONSTER {
  Bouftou
  Krabby
}

Table monsters {
  id integer [primary key]
  type MONSTER
}

Table monsters_entities {
  monster_id uuid [not null]
  entity_id integer [not null] // TODO make this pair unique
}


Enum ITEM {
  Sword
  Potion
}

Table items {
  id integer [primary key]
  type ITEM
}

Table items_entities {
  item_id uuid [not null]
  entity_id integer [not null] // TODO make this pair unique
}

/// Account

Ref {
    accounts.id > accounts_characters.account_id [delete: cascade, update: no action, color: #79AD51]
}

Ref {
    accounts_characters.character_id > characters.id [delete: cascade, update: no action, color: #79AD51]
}

/// Characters

Ref {
    characters.id > characters_entities.characters_id [delete: cascade, update: no action, color: #79AD51]
}

Ref {
   characters_entities.entity_id > entities.id [delete: cascade, update: no action, color: #79AD51]
}

/// Items
Ref {
    items.id > items_entities.item_id [delete: cascade, update: no action, color: #79AD51]
}

Ref {
   items_entities.entity_id > entities.id [delete: cascade, update: no action, color: #79AD51]
}

/// Monster
Ref {
    monsters.id > monsters_entities.monster_id [delete: cascade, update: no action, color: #79AD51]
}

Ref {
   monsters_entities.entity_id > entities.id [delete: cascade, update: no action, color: #79AD51]
}

/// Entities
Ref {
   entities.id > locations.entity_id [delete: cascade, update: no action, color: #79AD51]
}