[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = { version = "0.5.3", features = ["std"] }
diesel = { version = "*", features = ["postgres", "uuid"] }
dotenvy = "0.15"
rand = "*"
tonic = "*"
prost = "*"
uuid = "1.15.1"
byteorder = "1.5.0"
serde_json = "*"
serde = {  version = "*", features = [ "derive" ] }

[dependencies.diesel_geometry]
git = "https://github.com/neeryapp/diesel_geometry.git"

[build-dependencies]
tonic-build = "*"
