use common::authenticator::Authenticator;
use common::database::model::character::PgClasses;

use crate::services::constants::*;
use common::character::{CharacterHandler, CharacterHandlerError};
use common::grpc_codegen::rpg_authenticate_server::RpgAuthenticate;
use common::grpc_codegen::{AuthReply, AuthRequest, EmptyReply, LogoutRequest};
use tonic::Response;

#[derive(Debug, Default)]
pub struct RpgAuthenticateService {}

#[tonic::async_trait]
impl RpgAuthenticate for RpgAuthenticateService {
    async fn authenticate_user(
        &self,
        request: tonic::Request<AuthRequest>,
    ) -> Result<tonic::Response<AuthReply>, tonic::Status> {
        let auth_req: AuthRequest = request.into_inner();
        println!("{}{:?}", AUTHENTICATE_USER_WITH, auth_req);

        let mut user = Authenticator::new(&auth_req.login);
        if !user.authenticate(&auth_req.password) {
            println!("{}{}", AUTHENTICATE_USER_ERROR, INVALID_LOGIN_PASSWORD);
            return Err(tonic::Status::invalid_argument(INVALID_LOGIN_PASSWORD));
        }

        // Session ID Token best practices from OWASP:
        // https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html
        // I tried to list, applicable web app best practices that could be implemented in our game server:
        //
        // _ : session id name should not be extremely descriptive
        // _ : session id token should use at least 64 bits of entropy / length
        // _ : session id token content should be meaningless to prevent disclosure
        // _ : unique token generated by a CSPRNG with size of at least 128 bits
        // _ : session inactivity timeout, to logout inactive users (server-side)
        // _ : session token renewal timeout, auto-renew the token without asking re-authentication
        // _ : session absolute timeout to force re-authentication
        // _ : TLS to avoid disclose the token (related to gRPC server or reverse proxy)
        // _ : Avoid persistent token, token should be drop at logout / rpg-client closure
        // _ : Use Strict session-management:
        //      _ : token should be generate server side
        //      _ : server should never accept token they have never generated
        // _ : Client/Server should provide manual logout and visible logout button
        // _ : Client can implement a maximum retry counter, with a timer when the maximum is reached
        // _ : Client can logout the user at window close event
        // _ : Bind session id token with user properties (ip address, OS, etc ...)
        // _ : Simultaneous login ideally should prompt user to choose what should be done:
        //     (Keep old session logout new session, Keep new and logout old)
        // Advanced measure:
        // _ : password / token bruteforce detection with single IP address
        let new_token = format!("{}-cafebab", auth_req.login);

        user.set_token(&new_token).map_err(|e| {
            println!("{}{}", AUTHENTICATE_USER_ERROR, e);
            tonic::Status::internal(e.to_string())
        })?;

        println!("{} token: {}", AUTHENTICATE_USER_SUCCESS, new_token);

        // Automate characters creation : for now only one character is allowed per account
        let success = Response::new(AuthReply { token: new_token });
        match CharacterHandler::new(&auth_req.login) {
            Ok(_) => {
                println!(
                    "{}A character already exist for {}",
                    CHARACTER_CREATION, auth_req.login
                );
                Ok(success)
            }
            Err(CharacterHandlerError::NoCharacterForAccount) => {
                if let Err(e) = CharacterHandler::create(
                    &auth_req.login,
                    &auth_req.login,
                    rand::random::<PgClasses>(),
                ) {
                    println!("{}failed with: {:?}", CHARACTER_CREATION, e);
                    Err(tonic::Status::internal(e.to_string()))
                } else {
                    println!("{}succeed.", CHARACTER_CREATION);
                    Ok(success)
                }
            }
            Err(e) => {
                println!(
                    "{}while retrieving Character for {}: {}",
                    AUTHENTICATE_USER_ERROR, auth_req.login, e
                );
                Err(tonic::Status::internal(e.to_string()))
            }
        }
    }

    async fn logout(
        &self,
        request: tonic::Request<LogoutRequest>,
    ) -> Result<tonic::Response<EmptyReply>, tonic::Status> {
        let logout_request: LogoutRequest = request.into_inner();
        println!("{}{:?}", LOGOUT_USER_WITH, logout_request);

        Authenticator::new(&logout_request.login)
            .logout(Some(logout_request.token.clone()))
            .map_err(|e| {
                println!("{}{}", LOGOUT_USER_ERROR, e);
                tonic::Status::internal("Logout failed")
            })
            .and_then(|_| {
                println!("{}", LOGOUT_USER_SUCCESS);
                Ok(Response::new(EmptyReply {}))
            })
    }
}
