use common::authenticator::Authenticator;

use common::character::CharacterAccountHandler;
use common::database::model::character::Classes;
use common::grpc_codegen::rpg_authenticate_server::RpgAuthenticate;
use common::grpc_codegen::{AuthReply, AuthRequest, EmptyReply, LogoutRequest};
use tonic::Response;

#[derive(Debug, Default)]
pub struct RpgAuthenticateService {}

#[tonic::async_trait]
impl RpgAuthenticate for RpgAuthenticateService {
    async fn authenticate_user(
        &self,
        request: tonic::Request<AuthRequest>,
    ) -> std::result::Result<tonic::Response<AuthReply>, tonic::Status> {
        let auth_req: AuthRequest = request.into_inner();
        println!("[Server]: [AuthenticateUser] : with: {:?}", auth_req);

        let mut user = Authenticator::new(&auth_req.login);
        if !user.authenticate(&auth_req.password) {
            println!("[Server]: [AuthenticateUser] : Error: Invalid login or password.");
            return Err(tonic::Status::invalid_argument("Invalid login or password"));
        }

        // Session ID Token best practices from OWASP:
        // https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html
        // I tried to list, applicable web app best practices that could be implemented in our game server:
        //
        // _ : session id name should not be extremely descriptive
        // _ : session id token should use at least 64 bits of entropy / length
        // _ : session id token content should be meaningless to prevent disclosure
        // _ : unique token generated by a CSPRNG with size of at least 128 bits
        // _ : session inactivity timeout, to logout inactive users (server-side)
        // _ : session token renewal timeout, auto-renew the token without asking re-authentication
        // _ : session absolute timeout to force re-authentication
        // _ : TLS to avoid disclose the token (related to gRPC server or reverse proxy)
        // _ : Avoid persistent token, token should be drop at logout / rpg-client closure
        // _ : Use Strict session-management:
        //      _ : token should be generate server side
        //      _ : server should never accept token they have never generated
        // _ : Client/Server should provide manual logout and visible logout button
        // _ : Client can implement a maximum retry counter, with a timer when the maximum is reached
        // _ : Client can logout the user at window close event
        // _ : Bind session id token with user properties (ip address, OS, etc ...)
        // _ : Simultaneous login ideally should prompt user to choose what should be done:
        //     (Keep old session logout new session, Keep new and logout old)
        // Advanced measure:
        // _ : password / token bruteforce detection with single IP address
        let new_token = format!("{}-cafebab", auth_req.login);

        return user
            .set_token(&new_token)
            .map_err(|e| {
                println!("[Server]: [AuthenticateUser] : Error: {}", e.to_string());
                tonic::Status::internal(e.to_string())
            })
            .and_then(|()| {
                println!(
                    "[Server]: [AuthenticateUser] : Success: token: {}",
                    new_token
                );
                // Automate characters creation :
                // for now only one character is allowed per account
                let mut account_characters = CharacterAccountHandler::new(auth_req.login.clone());
                account_characters
                    .get_all()
                    .map_err(|e| tonic::Status::internal(e.to_string()))
                    .and_then(|characters| {
                        let prefix = "[Server]: [AuthenticateUser] : [CreateCharacter]:";

                        if characters.is_empty() {
                            let res = account_characters.create(&auth_req.login, Classes::Warrior);
                            if let Err(e) = res {
                                println!("{} failed with: {:?}", prefix, e);
                                return Err(tonic::Status::internal(e.to_string()));
                            }
                            println!("{} succeed", prefix);
                        } else {
                            println!(
                                "{} A character already exist for {}",
                                prefix, auth_req.login
                            )
                        }
                        Ok(Response::new(AuthReply { token: new_token }))
                    })
            });
    }

    async fn logout(
        &self,
        request: tonic::Request<LogoutRequest>,
    ) -> std::result::Result<tonic::Response<EmptyReply>, tonic::Status> {
        let logout_request: LogoutRequest = request.into_inner();
        println!("[Server]: [LogoutUser] : with: {:?}", logout_request);

        let mut authenticator = Authenticator::new(&logout_request.login);
        if !authenticator.logout(Some(logout_request.token.clone())) {
            println!("[Server]: [LogoutUser] : Error: internal error");
            return Err(tonic::Status::internal("Logout failed"));
        }

        println!("[Server]: [LogoutUser] : Success");
        Ok(Response::new(EmptyReply {}))
    }
}
