name: Test pipeline

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  common-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prerequisite
        run: sudo apt-get install protobuf-compiler

      - name: Build
        run: cargo build --verbose -p common

      - name: Run tests
        run: cargo test --verbose -p common

  server-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prerequisite
        run: sudo apt-get install protobuf-compiler

      - name: Create test .env file
        run: |
          cat <<EOF > .env
          # Server
          RUST_BACKTRACE=1
          RUST_LOG=debug,h2=off

          # Postgres
          POSTGRES_USER=gh-action-test
          POSTGRES_PASSWORD=gh-action-test
          POSTGRES_DB=gh-action-test
          POSTGRES_HOST=gh-action-test-postgres

          # Test
          SESSION_TOKEN_EXPIRATION=2
          ACCOUNT_LOCK_TIME_1=1
          THROTTLING_TIME_WINDOW=2
          EOF

      - name: Build and run server and postgresql db
        run: docker compose up -d

      - name: Seed the database with tests data
        run: ./server/tests/seed.sh

      - name: Build
        run: cargo build --verbose -p server

      - name: Run tests
        run: RUST_BACKTRACE=1 cargo test --verbose -p server

      - name: Get containers logs
        if: always()
        run: docker compose logs --no-color

      - name: Clean
        run: docker compose down -v
